# Generated by Django 5.1.3 on 2024-12-13 11:16

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('fabric_type', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=90, scale=None, size=[1920, 1080], upload_to='fabric/')),
                ('per_meter_price', models.FloatField()),
                ('stok', models.FloatField(default=0)),
            ],
        ),
    ]
