# Generated by Django 5.1.3 on 2024-12-15 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='code',
            field=models.CharField(choices=[('USD', '$'), ('EUR', '€'), ('KGS', 'Лв'), ('TL', '₺')], default='USD', max_length=3),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='invoiceproduct',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoice.invoice'),
        ),
    ]
