# Generated by Django 5.1.3 on 2024-12-16 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_invoiceproduct_invoice_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceproduct',
            name='invoice_date',
        ),
        migrations.AlterField(
            model_name='invoiceproduct',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
