# Generated by Django 5.1.3 on 2024-12-20 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0006_remove_invoiceproduct_invoice_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoiceproduct',
            old_name='total_metre',
            new_name='roll_metre',
        ),
    ]
